### DISCUSSION TITLE
Anker Solix 2 Pro Smart Meter values

### DISCUSSION THREAD

**Discussion by Siddi2872** [thomluther/ha-anker-solix#117] [Q&A] [answered]
Hello Tom,

Thx for your great work with this Integration. I have a question about the Smart Meter values.
The smart meter measures the total power consumed in the house. This value can be seen in the Anker app. but the API only sends the two values "Grid Export" and "Grid Import"? Is there a way to get or calculate the value of the total power?

![IMG_0966](https://github.com/user-attachments/assets/2f2dfe73-27b2-45aa-86d3-01b6c657e9ba)
![IMG_0033](https://github.com/user-attachments/assets/cd6e9e0f-809b-47a0-81f2-0941fe67b61d)

Thx in advance

**Comment by thomluther** [comment]
Hi @Siddi2872 , the house demand is not a smart meter value, so you won't find it under the smart meter device.
It is calculated by the cloud and reported under the solarbank total values.
The integration does list it in the system values, I believe it is house consumption or house demand.

**Comment by Siddi2872** [comment]
Hi Tom,
I know what you mean. There are 3 entitys like that, but they are all showing the same value. The value for the Output from the Solarbank with 800 watts max. Not the value of the full house consumption.

**Reply by thomluther** [reply, marked as answer]
I checked this, actually they are created under the Solarbank device. If they are the same, then this is what the cloud returns usually, You can check the cloud values with the get system info service.
Here is the entity description for them. The json_key is the response field that is used for the sensor, the translation key will be converted to the translated name according your HA language.
home_load_power should be the response field you are looking for.
```python
    AnkerSolixSensorDescription(
        key="ac_to_home_load",
        translation_key="ac_to_home_load",
        json_key="to_home_load",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
        exclude_fn=lambda s, _: not ({SolixDeviceType.SOLARBANK.value} - s),
        check_invalid=True,
    ),
    AnkerSolixSensorDescription(
        key="home_load_power",
        translation_key="home_load_power",
        json_key="home_load_power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
        exclude_fn=lambda s, _: not ({SolixDeviceType.SMARTMETER.value} - s),
    ),
    AnkerSolixSensorDescription(
        key="ac_generate_power",
        translation_key="ac_generate_power",
        json_key="generate_power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
        suggested_display_precision=0,
        exclude_fn=lambda s, _: not ({SolixDeviceType.INVERTER.value} - s),
    ),
```

That should be the 'Hausbedarf' sensor of the SB2 device

**Reply by Fjury** [reply]
Hello Thomas,

I'am using your great Work in version 2.8.0.

For me there is no entity with the value we are looking for under the solarbank devices.
But I see the value we are looking for in the result of the following action:

```yaml
action: anker_solix.get_system_info
target:
entity_id: sensor.system_55_ertrag_gesamt
data:
include_cache: false
```

**home_load_power: "207"**

The sensor named system_55_ertrag_gesamt is available and show me the current value of:
statistics:
      - type: "1"
        total: "24.19"
        unit: kWh

But the value we are looking for is not available as attribute of sensor.system_55_ertrag_gesamt and also not available as single entity as part of the solarbank devices.

You can please help to get this value available in HomeAssistant. Maybe with the next update ;-)

Thx in advance


```yaml
sensor.system_55_ertrag_gesamt:
  system_info:
    home_info:
      home_name: Home
      home_img: ""
      charging_power: "0.00"
      power_unit: W
    solar_list: []
    pps_info:
      pps_list: []
      total_charging_power: "0.00"
      power_unit: W
      total_battery_power: "0.00"
      updated_time: ""
      pps_status: 0
    statistics:
      - type: "1"
        total: "24.19"
        unit: kWh
      - type: "2"
        total: "24.12"
        unit: kg
      - type: "3"
        total: "7.08"
        unit: €
    topology_type: "1"
    solarbank_info:
      solarbank_list:
        - device_pn: A17C5
          device_sn: APCDXXXXXXXXXXXXX
          device_name: Solarbank 3 E2700 Pro
          device_img: >-
            https://public-aiot-fra-prod.s3.dualstack.eu-central-1.amazonaws.com/anker-power/public/product/2025/04/15/iot-admin/6SO8wjMetOwT8PaH/picl_A17C5_normal.png
          battery_power: "23"
          bind_site_status: ""
          charging_power: "249"
          power_unit: W
          charging_status: "0"
          status: "1"
          wireless_type: "1"
          main_version: ""
          photovoltaic_power: "720"
          output_power: "249"
          create_time: 1749493256
          set_load_power: ""
          sub_package_num: 1
          output_cutoff_data: 0
          is_display: true
          bat_charge_power: "471"
      total_charging_power: "471"
      power_unit: W
      charging_status: "0"
      total_battery_power: "0.23"
      updated_time: "2025-06-14 12:28:42"
      total_photovoltaic_power: "720"
      total_output_power: "249.00"
      display_set_power: false
      battery_discharge_power: "0"
      ac_power: "0"
      to_home_load: "0"
      is_display_data: true
      solar_power_1: "365"
      solar_power_2: "355"
      solar_power_3: "0"
      solar_power_4: "0"
      other_input_power: "0"
      micro_inverter_power: "0"
      micro_inverter_power_limit: "0"
      micro_inverter_low_power_limit: "0"
      grid_to_battery_power: "0"
      pei_heating_power: "0"
      backup_info:
        start_time: 0
        end_time: 0
        full_time: 0
      use_time_excute_info:
        current_band: "0"
    retain_load: 250W
    scene_mode: 3
    home_load_power: "207"
    updated_time: 01-01-0001 00:00:00
    power_site_type: 12
    site_id: 42934a52-4073-415b-826c-483c22d2887d
    powerpanel_list: []
    grid_info:
      grid_list:
        - device_pn: A17X7
          device_sn: AUJS020F07111921
          device_name: Smart Meter
          device_img: ""
          create_time: 1749733612
          status: "1"
          bind_site_status: ""
          wireless_type: ""
      photovoltaic_to_grid_power: "42"
      grid_to_home_power: "0"
      grid_status: 0
      has_history_data: true
    is_downgrade: false
    error_code: 0
    smart_plug_info: null
    feature_switch:
      0w_feed_v2: true
      enable_timeslot: true
      exceed_power: false
      heating: false
      plug_switch_report: true
    other_loads_power: "207"
    priority_discharge_switch: 0
    display_priority_discharge_tips: 0
    priority_discharge_upgrade_devices: ""
    style_id: 0
    is_show_priority_discharge: 0
    solarbank_pps_info:
      pps_list: null
      total_charging_power: ""
      total_output_power: ""
      total_battery_power: ""
      total_pv_input_power: ""
      total_home_load_power: ""
      total_grid_to_battery: ""
    user_scene_mode: 3
    is_dynamic_price_down_grade: false
    aiems_profit: null
    switch_0w: 0

```

**Reply by thomluther** [reply]
Hi, all the values you mention are available in the integration. Home load is actually the calculated home demand by the Anker cloud. This belongs to the system device and is only calculated while Solarbank is not on standby mode to my knowledge.
The statistic values are also under the system device where they belong to.

**Reply by thomluther** [reply]
If there is still something missing in system or solarbank device, you need to attach a system export zip and tell me which the value you are missing from the export. I can than double check after vacation.

**Reply by thomluther** [reply]
Actually there seems to be a mismatch in the sensor definitions. The home load demand is defined as device sensor, but the home load value is never added to the device cache. Need to think about whether this should be reported as device or system sensor and fix that in a future release.

**Reply by Fjury** [reply]
Hey Thomas,

thx for your reply.

Could it be that this is related to Solarbank3, differs slightly from the other Solarbanks and is therefore not displayed?

The "AC house output"/"AC Hausabgabe" value remain constant at 0W.

The value must show 3857 W.


Let me know if I can send you the debug log or any other information.



<img width="1433" alt="Bildschirmfoto 2025-06-14 um 20 47 00" src="https://github.com/user-attachments/assets/cda0bdc3-0ae7-434d-ba64-692e43bf2001" />


```yaml
sensor.system_55_ertrag_gesamt:
  system_info:
    home_info:
      home_name: Home
      home_img: ""
      charging_power: "0.00"
      power_unit: W
    solar_list: []
    pps_info:
      pps_list: []
      total_charging_power: "0.00"
      power_unit: W
      total_battery_power: "0.00"
      updated_time: ""
      pps_status: 0
    statistics:
      - type: "1"
        total: "27.41"
        unit: kWh
      - type: "2"
        total: "27.33"
        unit: kg
      - type: "3"
        total: "7.65"
        unit: €
    topology_type: "1"
    solarbank_info:
      solarbank_list:
        - device_pn: A17C5
          device_sn: APCDXXXXXXXXXXX
          device_name: Solarbank 3 E2700 Pro
          device_img: >-
            https://public-aiot-fra-prod.s3.dualstack.eu-central-1.amazonaws.com/anker-power/public/product/2025/04/15/iot-admin/6SO8wjMetOwT8PaH/picl_A17C5_normal.png
          battery_power: "36"
          bind_site_status: ""
          charging_power: "249"
          power_unit: W
          charging_status: "0"
          status: "1"
          wireless_type: "1"
          main_version: ""
          photovoltaic_power: "55"
          output_power: "249"
          create_time: 1749493256
          set_load_power: ""
          sub_package_num: 1
          output_cutoff_data: 0
          is_display: true
          bat_charge_power: "0"
      total_charging_power: "0"
      power_unit: W
      charging_status: "0"
      total_battery_power: "0.36"
      updated_time: "2025-06-14 20:47:01"
      total_photovoltaic_power: "55"
      total_output_power: "249.00"
      display_set_power: false
      battery_discharge_power: "194"
      ac_power: "0"
      to_home_load: "0"
      is_display_data: true
      solar_power_1: "55"
      solar_power_2: "0"
      solar_power_3: "0"
      solar_power_4: "0"
      other_input_power: "0"
      micro_inverter_power: "0"
      micro_inverter_power_limit: "0"
      micro_inverter_low_power_limit: "0"
      grid_to_battery_power: "0"
      pei_heating_power: "0"
      backup_info:
        start_time: 0
        end_time: 0
        full_time: 0
      use_time_excute_info:
        current_band: "0"
    retain_load: 250W
    scene_mode: 3
    home_load_power: "3857"
    updated_time: 01-01-0001 00:00:00
    power_site_type: 12
    site_id: 42934a52-4073-415b-826c-483c22d2887d
    powerpanel_list: []
    grid_info:
      grid_list:
        - device_pn: A17X7
          device_sn: AUJS020F07111921
          device_name: Smart Meter
          device_img: ""
          create_time: 1749733612
          status: "1"
          bind_site_status: ""
          wireless_type: ""
      photovoltaic_to_grid_power: "0"
      grid_to_home_power: "3608"
      grid_status: 0
      has_history_data: true
    is_downgrade: false
    error_code: 0
    smart_plug_info: null
    feature_switch:
      0w_feed_v2: true
      enable_timeslot: true
      exceed_power: false
      heating: false
      plug_switch_report: true
    other_loads_power: "3857"
    priority_discharge_switch: 0
    display_priority_discharge_tips: 0
    priority_discharge_upgrade_devices: ""
    style_id: 0
    is_show_priority_discharge: 0
    solarbank_pps_info:
      pps_list: null
      total_charging_power: ""
      total_output_power: ""
      total_battery_power: ""
      total_pv_input_power: ""
      total_home_load_power: ""
      total_grid_to_battery: ""
    user_scene_mode: 3
    is_dynamic_price_down_grade: false
    aiems_profit: null
    switch_0w: 0

```
