### DISCUSSION TITLE
Tibber integration

### DISCUSSION THREAD

**Discussion by BerndMueDev** [thomluther/ha-anker-solix#236] [Q&A] [answered]
Hi! 
Thanks for this great project. 
Is it possible to use Tibber's current electricity prices to calculate the cost savings?

**Comment by thomluther** [comment, marked as answer]
Hi, sure this is possible. With HA you can do almost anything,
You will have to google around how to accomplish this.
This is completely independent of the integration.

I think you will need a helper that calculates the current price

I have something similar to calculate the savings of my system with the fix price from an input helper.

These are sensors in the temple section of the configuration. You could also create them in the UI meanwhile as template helper. You only need the state template and the rest you can adjust in the UI.
```yaml
# Sensoren für laufende Ersparnis in Euro pro Stunde, basierend auf dem aktuellen Strompreis in EUR/kWh
- sensor:
    - name: BKW Vorteil
      unique_id: "BkwVorteil"
      unit_of_measurement: "€/h"
      state: >
        {{ states('sensor.bkw_eigenverbrauch')|float(0) * states('input_number.aktueller_strompreis')|float(0)/1000 }}

    - name: Akku Vorteil
      unique_id: "AkkuVorteil"
      unit_of_measurement: "€/h"
      state: >
        {% if states('sensor.solarbank_status') == 'discharge' %}
          {{ states('sensor.bkw_eigenverbrauch')|float(0) * states('input_number.aktueller_strompreis')|float(0)/1000 }}
        {% else %}
          {{0}}
        {% endif %}

```
Then you need integration helper to integrate those sensors, which will give you a total_increasing € sensor. Don't use the k prefix with the integral sensor, otherwise it would show you k€.
