### DISCUSSION TITLE
Self-consumption | Device output setting

### DISCUSSION THREAD

**Discussion by RAFDAVID** [thomluther/ha-anker-solix#259] [Q&A] [answered]
Hi,
I have got a SB2 pro and I search the entitie in HA to change the power output when you used smart meter.
It's named 'Device Output Setting' in the Anker app and you can choose between 350, 600, 800 or 1000W.
Could you help me please ?
Thanks

**Comment by thomluther** [comment, marked as answer]
Hello
There is not data point or Api endpoint known for this setting which you are referring to. That setting is the inverter limit, not the system output setting. So it is not supported via Api library or integration at this point in time.
You may try using the Action for Api requests and see if you find any enpoints/parameters that will show or change the inverter limit setting.

There is one for the [MI80 inverter](https://github.com/thomluther/anker-solix-api/issues/186) which still has to be [tested and validated by someone like you for SB2](https://github.com/thomluther/ha-anker-solix/discussions/255). I don't know if that works for the SB2 inverter as well.

It may be completely different endpoints (if supported at all via Api)

The existing system output entity is not working for Smart Meter mode, only for the manual usage mode, or as additional output setting in the Smart Plug mode. It only changes the manual or smart plug plan for the active slot when you apply the change.

**Reply by RAFDAVID** [reply]
Thanks for your reply

**Comment by RAFDAVID** [comment]
Hello @thomluther,
I've tested 2 things, look at the attached files  :
- get_site_list, it's working well.
<img width="742" alt="Getssitelist" src="https://github.com/user-attachments/assets/2a567984-dc3a-492c-83e4-b9a8e21c980a" />
- getPvTotalStatistics, doesn't work !
<img width="743" alt="getPvTotalStatistics" src="https://github.com/user-attachments/assets/8c26273c-0f8c-4386-86fd-6645e20f719e" />

I might have made a mistake, maybe you can help me !

**Reply by thomluther** [reply]
Hi, yes you have to look to the response.
payload contains what you sent to the server.
You don't need the device_sn or site_id fields for this endpoint, but it expects a 'sn' field.
So replace the device_sn with sn and remove the site_id and try again.
It might be easier to paste the action output text as code block here instead of screenshots. Then you can also easily replace personal data...and it contains already your request data from the action. 
The error field in the action response is shown only since no valid response was received, otherwise you would see the Api response object.

**Reply by RAFDAVID** [reply]
Hi,
The request works, I can change the power (600W or 800W), but I don't think it's the output power of SB2 because I can't set 350W or 1000W.
```yaml
switch.rap_fr_utilisation_de_l_api:
  request:
    server: https://ankerpower-api-eu.anker.com
    method: post
    endpoint: charging_pv_svc/set_aps_power
    payload:
      sn: APxxxxxxxxxxx
      power: 800
  response:
    code: 0
    msg: success!
    data:
      messageId: ""
      success: true
    trace_id: ""
```
When I'm in the app, my output is limited to 350W even if the set_aps_power is 800W.
![Img_2025_05_01_14_03_15](https://github.com/user-attachments/assets/1bb8ba19-3ec4-4229-b112-a9381411ccf4)

The request getPvTotalStatistics don't work.
```yaml
switch.rap_fr_utilisation_de_l_api:
  request:
    server: https://ankerpower-api-eu.anker.com
    method: post
    endpoint: charging_pv_svc/getPvTotalStatistics
    payload:
      sn: APxxxxxxxxxxxx
  response:
    code: -1
    msg: Failed to request.
    trace_id: ""
```
