### ISSUE TITLE
Add support for anker prime 250w

### ISSUE THREAD

**Issue by Alexandre006** [thomluther/ha-anker-solix#264]
### Checklist

- [x] I have filled out the template to the best of my ability.
- [x] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [x] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

No, this is not a problem. I only want to integrate the anker prime 250w charger. Within the home assistant application.

### Describe the solution you'd like

<img width="948" alt="Image" src="https://github.com/user-attachments/assets/a88b8961-7de3-473d-acc1-48bdf9c40c3c" />

At the moment, here's what they're getting back from the anker integration for this charger. Unfortunately, the 6 usb ports are not included in the integration.

### Describe alternatives you've considered

The anker application provides the following functions for load ports 

![Image](https://github.com/user-attachments/assets/1df43ec3-c291-4f46-ac09-4906edb78e36)

### Additional context

No

**Comment by thomluther** [comment]
Hi @Alexandre006 thanks for your request, but I doubt this is possible.
Such stand alone devices barely report anything to the power cloud, only via the MQTT cloud where not interface exists.
You may try to explore following endpoints with your HA integration when using the main account https://github.com/thomluther/anker-solix-api/blob/2d2c2808323174cab7a42cde05f0c68e7e2319ed/api/apitypes.py#L291:
```
related to Prime charger models: 11 + 0 used => 11 total
    'mini_power/v1/app/charging/get_charging_mode_list',
    'mini_power/v1/app/charging/update_charging_mode',
    'mini_power/v1/app/charging/add_charging_mode',
    'mini_power/v1/app/charging/delete_charging_mode',
    'mini_power/v1/app/setting/set_charging_mode_status',
    'mini_power/v1/app/egg/get_easter_egg_trigger_list',
    'mini_power/v1/app/egg/add_easter_egg_trigger_record',
    'mini_power/v1/app/egg/report_easter_egg_trigger_status',
    'mini_power/v1/app/setting/get_device_setting',
    'mini_power/v1/app/power/get_day_power_data',
    'mini_power/v1/app/style/get_clock_screensavers',  # works for {'product_code': 'A2345'} => Prime charger
```

But I don't think they will report the actual power values...If you are lucky, you can find some specific settings and eventually also how those settings can be modified. You will need to 'interpret' any values when comparing them with the App.

**Comment by thomluther** [comment]
@Alexandre006 , did you find any interesting data with those endpoints?  Can you provide example?

**Comment by ShonP40** [comment]
@thomluther I tried some of those endpoints on my charger and here's what I got:

`mini_power/v1/app/charging/get_charging_mode_list`:
```yaml
switch.shonp40_api_usage:
  request:
    server: https://ankerpower-api-eu.anker.com
    method: post
    endpoint: mini_power/v1/app/charging/get_charging_mode_list
    payload:
      device_sn: <redacted>
      device_model: A2345
      product_code: A2345
  response:
    code: 0
    msg: success!
    data:
      charging_mode_list: []
    trace_id: <redacted>
```

`mini_power/v1/app/egg/get_easter_egg_trigger_list`:
```yaml
switch.shonp40_api_usage:
  request:
    server: https://ankerpower-api-eu.anker.com
    method: post
    endpoint: mini_power/v1/app/egg/get_easter_egg_trigger_list
    payload:
      device_sn: <redacted>
      device_model: A2345
      product_code: A2345
  response:
    code: 0
    msg: success!
    data:
      egg_trigger_list:
        - egg_type: 1
          trigger_time: 1734969388
          status: 1
        - egg_type: 2
          trigger_time: 1734969738
          status: 1
        - egg_type: 3
          trigger_time: 1734969851
          status: 1
        - egg_type: 4
          trigger_time: 1734969461
          status: 1
        - egg_type: 5
          trigger_time: 1734969037
          status: 1
    trace_id: <redacted>
```

`mini_power/v1/app/setting/get_device_setting`:
```yaml
switch.shonp40_api_usage:
  request:
    server: https://ankerpower-api-eu.anker.com
    method: post
    endpoint: mini_power/v1/app/setting/get_device_setting
    payload:
      device_sn: <redacted>
      device_model: A2345
      product_code: A2345
  response:
    code: 0
    msg: success!
    data:
      device_setting:
        charging_mode_status: 1
        compatibility_status: 0
    trace_id: <redacted>
```

`mini_power/v1/app/style/get_clock_screensavers`:
```yaml
switch.shonp40_api_usage:
  request:
    server: https://ankerpower-api-eu.anker.com
    method: post
    endpoint: mini_power/v1/app/style/get_clock_screensavers
    payload:
      device_sn: <redacted>
      device_model: A2345
      product_code: A2345
  response:
    code: 0
    msg: success!
    data:
      category:
        - id: Futuristic
          category_name: Futuristic
          list:
            - id: "948897111"
              title: Celestial
              image_url: >-
                https://public-aiot-ore-qa.s3.dualstack.us-west-2.amazonaws.com/anker-power/public/banner/2025/03/26/iot-admin/T5IyObNNgxhUVPH8/%E6%B0%94%E6%B3%A1.jpg
              file_crc32: "0x40914327"
              text_color: ""
              bin_url: ""
            - id: "236632206"
              title: Robotic
              image_url: >-
                https://public-aiot-ore-qa.s3.dualstack.us-west-2.amazonaws.com/anker-power/public/banner/2025/03/26/iot-admin/ZOXFASuOK3154M0O/%E6%9C%BA%E7%94%B2.jpg
              file_crc32: "0x756eab66"
              text_color: ""
              bin_url: ""
        - id: Cosmic
          category_name: Cosmic
          list:
            - id: "938963984"
              title: Lunar
              image_url: >-
                https://public-aiot-ore-qa.s3.dualstack.us-west-2.amazonaws.com/anker-power/public/banner/2025/03/26/iot-admin/dTHYjLQQJXwkoXJC/%E6%9C%88%E7%90%83.jpg
              file_crc32: "0xbd2ddca7"
              text_color: ""
              bin_url: ""
            - id: "819158638"
              title: Galactic
              image_url: >-
                https://public-aiot-ore-qa.s3.dualstack.us-west-2.amazonaws.com/anker-power/public/banner/2025/03/26/iot-admin/z0pv3dszhjkAYSfc/%E6%98%9F%E4%BA%91.jpg
              file_crc32: "0xdab95e74"
              text_color: ""
              bin_url: ""
            - id: "95294588"
              title: Meteorite
              image_url: >-
                https://public-aiot-ore-qa.s3.dualstack.us-west-2.amazonaws.com/anker-power/public/banner/2025/03/26/iot-admin/xNe6kVzxj3C1aRKh/%E6%B5%81%E6%98%9F%E9%9B%A8.jpg
              file_crc32: "0x2c1f806"
              text_color: ""
              bin_url: ""
        - id: Artistic
          category_name: Artistic
          list:
            - id: "130254227"
              title: Floral Waltz
              image_url: >-
                https://public-aiot-ore-qa.s3.dualstack.us-west-2.amazonaws.com/anker-power/public/banner/2025/03/26/iot-admin/dC2FoNMaEcpGz2kh/%E8%8A%B1%E4%B9%8B%E8%88%9E.jpg
              file_crc32: "0xde0cfff4"
              text_color: ""
              bin_url: ""
            - id: "347235639"
              title: Impressionist Bloom
              image_url: >-
                https://public-aiot-ore-qa.s3.dualstack.us-west-2.amazonaws.com/anker-power/public/banner/2025/03/26/iot-admin/P51puX6BWUwIbi7m/%E8%8E%AB%E5%A5%88%E8%8A%B1%E5%9B%AD.jpg
              file_crc32: "0x92800b00"
              text_color: ""
              bin_url: ""
        - id: Lively
          category_name: Lively
          list:
            - id: "172033515"
              title: Sweet Treats
              image_url: >-
                https://public-aiot-ore-qa.s3.dualstack.us-west-2.amazonaws.com/anker-power/public/banner/2025/03/26/iot-admin/dRHwN3JaCBmkEQyw/%E7%BC%A4%E7%BA%B7%E7%B3%96%E6%9E%9C.jpg
              file_crc32: "0x509eeca5"
              text_color: ""
              bin_url: ""
            - id: "496957652"
              title: Rhythmic Hue
              image_url: >-
                https://public-aiot-ore-qa.s3.dualstack.us-west-2.amazonaws.com/anker-power/public/banner/2025/03/26/iot-admin/6CF299B2kJQMth5E/%E8%B7%83%E5%8A%A8%E6%97%8B%E5%BE%8B.jpg
              file_crc32: "0xb5d0abf9"
              text_color: ""
              bin_url: ""
    trace_id: <redacted>
```

**Comment by thomluther** [comment]
@ShonP40 Thanks for the output so far. I shows that those endpoints are for the charger,
But at the end, this is all cryptic to me. If you cannot interpret something meaningful to your device settings, it probably does not make sense to implement something.
Can you select screensavers for your device? If you find the query and parameters to set a screen saver from the list to your device, that would be something that may make sense to implement. But I'm afraid you don't get real time consumption data. Maybe you can get some energy statistics from the cloud? Then I could implement a work around and implement average power values for the last interval that is resolved by the cloud stats.

If you test queries, it is important to validate what the minimum parameters are. Extra parameters are simply ignored, but they should not be implemented in the Api library if they are not necessary for the endpoint.

I assume you cannot share that device with another account like it is possible with a power system? There is no power system possible for the charger devices, so I don't think it can be shared with another account?

**Comment by thomluther** [comment]
More questions:
The endpoints indicate that you can create charging modes and toggle them. If you don't create one, the list will be empty of course. That might be something to intergrate into HA, at least toggling between defined modes...
```
    'mini_power/v1/app/charging/get_charging_mode_list',
    'mini_power/v1/app/charging/update_charging_mode',
    'mini_power/v1/app/charging/add_charging_mode',
    'mini_power/v1/app/charging/delete_charging_mode',
    'mini_power/v1/app/setting/set_charging_mode_status',
``` 

No idea what those 'easter eggs' are!?!

For energy stats you may need deeper testing of this endpoint:
` 'mini_power/v1/app/power/get_day_power_data',`

Since it is now possible to use the same account in HA and the App, parallel monitoring of energy data might become possible for charger devices. I would have to create a virtual system for them like for the standalone inverters, that have no system either but still report energy stats to the cloud.

**Comment by thomluther** [comment]
@ShonP40 , I made a few tests with my client without having such a device. It shows that those queries only need the 'device_sn' fields, except 'mini_power/v1/app/style/get_clock_screensavers' which also needs 'product_code'.
Can you please confirm they work with those minimum parameters?

For the daily stats, I only come to this payload, then get an error either because day format is wrong or I have no device with data in the cloud.
```yaml
endpoint: "mini_power/v1/app/power/get_day_power_data"
payload:
  device_sn: <deviceSn>
  device_model: "A2345"
  date: "2025-07-27"
```
Can you confirm and explore more with the day_power data to find correct format of query?
Once you confirm, I can add those to the export module in the first step to collect such data.
If you can configure your device in a way that produces output for those queries, we can see what else is possible.

**Comment by thomluther** [comment]
There is also a query for easter egg trigger status, which should look like this, maybe based on output of trigger list?
```yaml
endpoint: "mini_power/v1/app/egg/report_easter_egg_trigger_status"
payload: 
  device_sn: <deviceSn>
  report_time: 1734969388
  egg_type: 1
```
where egg_type is given in the list and report_time is Unix Epoche timestamp, not sure if related to the trigger time in the list...

**Comment by ShonP40** [comment]
I'll check it in a few days
Don't have time for it atm

**Comment by ShonP40** [comment]
> I assume you cannot share that device with another account like it is possible with a power system? There is no power system possible for the charger devices, so I don't think it can be shared with another account?

Nope, you can't

> No idea what those 'easter eggs' are!?!

Basically achievements you unlock by completing tasks (e.g using all ports at once), they don't expose any settings, just display a short animation once you get them.

> Can you please confirm they work with those minimum parameters?

Yep, they do. Just kept those there while I was testing

> Can you confirm and explore more with the day_power data to find correct format of query?

Just getting `Failed to request.` Guessing that they're using some different date format? (I tried today's and yesterday's days)

> There is also a query for easter egg trigger status, which should look like this, maybe based on output of trigger list?

```yaml
action: anker_solix.api_request
data:
  method: post
  payload:
    device_sn: <redacted>
    egg_type: 1
    report_time: 1734969388
  endpoint: mini_power/v1/app/egg/report_easter_egg_trigger_status
target:
  entity_id: switch.shonp40_api_usage

switch.shonp40_api_usage:
  request:
    server: https://ankerpower-api-eu.anker.com
    method: post
    endpoint: mini_power/v1/app/egg/report_easter_egg_trigger_status
    payload:
      device_sn: <redacted>
      egg_type: 1
      report_time: 1734969388
  response:
    code: 0
    msg: success!
    data: {}
    trace_id: <redacted>
```

**Comment by thomluther** [comment]
Date Format is either '2025-08-22' or the Unix timestamp as int or str.
If you query a month range it can also be '2025-08' usually. Keep trying various types, wrong type is typically rejected with error for expected type. Then it's just a matter finding the right format.
But that query seems to be the only one that could provide at least energy, while no real time power I guess.

**Comment by ShonP40** [comment]
its none of those
but all I do know is that it wants a string
```
response=type mismatch for field "date", expect "string", actual "string"
```

**Comment by thomluther** [comment]
ok, then maybe
Epoch timestamp: "1755828000"
Timestamp in milliseconds: "1755828000000"

**Comment by ShonP40** [comment]
Same error with both

**Comment by thomluther** [comment]
You could also try start_time and end_time or only time as additional fields. I don't know if they will be ignored or may make a difference. Its on you to find the right parameters and format to get hopefully something useful out of it.
The easter egg stuff is probably not relevant, but if you query them with the report_time, I guess that timestamp must match with something on your account or what you get from the list. If you used my example timestamp, it would not show anything in the response as you have seen already.

**Comment by spitfire** [comment]
```yaml
- id: Futuristic
          category_name: Futuristic
          list:
            - id: "948897111"
              title: Celestial
              image_url: >-
                https://public-aiot-ore-qa.s3.dualstack.us-west-2.amazonaws.com/anker-power/public/banner/2025/03/26/iot-admin/T5IyObNNgxhUVPH8/%E6%B0%94%E6%B3%A1.jpg
              file_crc32: "0x40914327"
              text_color: ""
              bin_url: ""
            - id: "236632206"
              title: Robotic
              image_url: >-
                https://public-aiot-ore-qa.s3.dualstack.us-west-2.amazonaws.com/anker-power/public/banner/2025/03/26/iot-admin/ZOXFASuOK3154M0O/%E6%9C%BA%E7%94%B2.jpg
              file_crc32: "0x756eab66"
              text_color: ""
              bin_url: ""
        - id: Cosmic
          category_name: Cosmic
          list:
            - id: "938963984"
              title: Lunar
              image_url: >-
                https://public-aiot-ore-qa.s3.dualstack.us-west-2.amazonaws.com/anker-power/public/banner/2025/03/26/iot-admin/dTHYjLQQJXwkoXJC/%E6%9C%88%E7%90%83.jpg
              file_crc32: "0xbd2ddca7"
              text_color: ""
              bin_url: ""
            - id: "819158638"
              title: Galactic
              image_url: >-
                https://public-aiot-ore-qa.s3.dualstack.us-west-2.amazonaws.com/anker-power/public/banner/2025/03/26/iot-admin/z0pv3dszhjkAYSfc/%E6%98%9F%E4%BA%91.jpg
              file_crc32: "0xdab95e74"
              text_color: ""
              bin_url: ""
            - id: "95294588"
              title: Meteorite
              image_url: >-
                https://public-aiot-ore-qa.s3.dualstack.us-west-2.amazonaws.com/anker-power/public/banner/2025/03/26/iot-admin/xNe6kVzxj3C1aRKh/%E6%B5%81%E6%98%9F%E9%9B%A8.jpg
              file_crc32: "0x2c1f806"
              text_color: ""
              bin_url: ""
        - id: Artistic
          category_name: Artistic
          list:
            - id: "130254227"
              title: Floral Waltz
              image_url: >-
                https://public-aiot-ore-qa.s3.dualstack.us-west-2.amazonaws.com/anker-power/public/banner/2025/03/26/iot-admin/dC2FoNMaEcpGz2kh/%E8%8A%B1%E4%B9%8B%E8%88%9E.jpg
              file_crc32: "0xde0cfff4"
              text_color: ""
              bin_url: ""
            - id: "347235639"
              title: Impressionist Bloom
              image_url: >-
                https://public-aiot-ore-qa.s3.dualstack.us-west-2.amazonaws.com/anker-power/public/banner/2025/03/26/iot-admin/P51puX6BWUwIbi7m/%E8%8E%AB%E5%A5%88%E8%8A%B1%E5%9B%AD.jpg
              file_crc32: "0x92800b00"
              text_color: ""
              bin_url: ""
        - id: Lively
          category_name: Lively
          list:
            - id: "172033515"
              title: Sweet Treats
              image_url: >-
                https://public-aiot-ore-qa.s3.dualstack.us-west-2.amazonaws.com/anker-power/public/banner/2025/03/26/iot-admin/dRHwN3JaCBmkEQyw/%E7%BC%A4%E7%BA%B7%E7%B3%96%E6%9E%9C.jpg
              file_crc32: "0x509eeca5"
              text_color: ""
              bin_url: ""
            - id: "496957652"
              title: Rhythmic Hue
              image_url: >-
                https://public-aiot-ore-qa.s3.dualstack.us-west-2.amazonaws.com/anker-power/public/banner/2025/03/26/iot-admin/6CF299B2kJQMth5E/%E8%B7%83%E5%8A%A8%E6%97%8B%E5%BE%8B.jpg
              file_crc32: "0xb5d0abf9"
              text_color: ""
              bin_url: ""
```
these sound like themes you can set on device's screen (from Anker's app):

<img width="1179" height="2556" alt="Image" src="https://github.com/user-attachments/assets/cf6ccd62-900d-4dbc-a517-b53b3a5e9563" />


```yaml
switch.shonp40_api_usage:
  request:
    server: https://ankerpower-api-eu.anker.com
    method: post
    endpoint: mini_power/v1/app/egg/report_easter_egg_trigger_status
    payload:
      device_sn: <redacted>
      egg_type: 1
      report_time: 1734969388
  response:
    code: 0
    msg: success!
    data: {}
    trace_id: <redacted>
```

and these are easter eggs/achievements you can unlock by using the device.

<img width="1179" height="2556" alt="Image" src="https://github.com/user-attachments/assets/5e39235a-ab09-45dd-864b-6c15006f10a2" />

I wonder if there's useful data controls somewhere?

**Comment by spitfire** [comment]
```yaml
switch.shonp40_api_usage:
  request:
    server: https://ankerpower-api-eu.anker.com
    method: post
    endpoint: mini_power/v1/app/setting/get_device_setting
    payload:
      device_sn: <redacted>
      device_model: A2345
      product_code: A2345
  response:
    code: 0
    msg: success!
    data:
      device_setting:
        charging_mode_status: 1
        compatibility_status: 0
```

Charging modes are listed here:
<img width="1179" height="2556" alt="Image" src="https://github.com/user-attachments/assets/36bd7db1-12f0-43d3-8014-2f5b9e26deb6" />

And there's compatibility mode for charging that you can set there too.

Are these read only APIs?

**Comment by thomluther** [comment]
There are a couple of other endpoints you have to try:
```python
    'mini_power/v1/app/charging/update_charging_mode',
    'mini_power/v1/app/charging/add_charging_mode',
    'mini_power/v1/app/charging/delete_charging_mode',
    'mini_power/v1/app/setting/set_charging_mode_status',
    'mini_power/v1/app/egg/add_easter_egg_trigger_record',
    'mini_power/v1/app/egg/report_easter_egg_trigger_status', # {"device_sn": deviceSn, "report_time": 1734969388, "egg_type": 1}
    'mini_power/v1/app/setting/set_compatibility_status',
```

**Comment by Technifocal** [comment]
I'd like to see this implemented, so if there's anything I can do to help please let me know.

Regarding your endpoint requests, playing around with `mini_power/v1/app/charging/update_charging_mode` seems to require a format similar to this:

```yaml
id: 1
name: "test"
total_power: 300
max_total_power: 300
auto_exit: 1
power_settings: [{"name": "test power setting", "power": 300, "max_power": 300}]
```

Resulting in:
```yaml
error: >-
    Api Client Error: <class
    'custom_components.anker_solix.solixapi.errors.RequestError'>: (10000) Anker
    Api Error: Failed to request.
```
Which is the same error message as when I try `mini_power/v1/app/egg/report_easter_egg_trigger_status` with the parameters listed above (I do not receive a success).

Lacking any of these fields throws an error (for example, removing `power_settings`):
```yaml
 error: >-
    Api Connection Error: ("Api Request Error: 400, message='Bad Request',
    url='https://ankerpower-api-eu.anker.com/mini_power/v1/app/charging/update_charging_mode'",
    'response=type mismatch for field "power_settings"\n')
```

I have no idea if any of these parameters are correct though, may I ask where you're getting the endpoints from?
